### ISSUE TITLE
Yellow circles in rural areas: poles, not boxes, and not all poles shown

### ISSUE THREAD

**Issue by jidanni** [kiang/taipower_feeder#2]
![9020-3](https://user-images.githubusercontent.com/1230959/83952326-c991d980-a86a-11ea-8811-f4b71799b837.jpg)
> 縣市後會顯示該縣市的所有變電箱點位（黃色圓點）

此處是桿非箱，且僅看到每第五枝。恐選之亦無反應。

[真相](https://www.openstreetmap.org/#map=19/24.17955/120.86766&layers=D).

**Comment by kiang** [comment]
應該是台電定義的再生能源可接入點，市區為變電箱，郊區為電線桿

**Comment by jidanni** [comment]
啊！是掛變壓器（油桶）之桿！
